### ISSUE TITLE
大佬，升级2023.6.0以后，实体全部不可用，如图

### ISSUE THREAD

**Issue by gzzyyt** [c1pher-cn/heweather#10]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/a6c9d9b6-778a-4e47-9e0d-a36dd7733f02)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/c8f216a5-d0f2-477a-be51-49998eaf0290)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/59f2e60a-f5e7-4d3c-ab18-f72d905df65a)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/5aa23603-bad5-4b7f-92b3-52c793d63387)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/50596983-77a5-4003-bb27-8e2d6b5ab515)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/7d25ffdc-5285-429f-99d9-a7fc001e9191)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/1838e390-c53f-4475-ae8b-e71ac5d21174)

**Comment by gzzyyt** [comment]
@c1pher-cn 望修复！

**Comment by c1pher-cn** [comment]
好的我升级看看。。。。干嘛那么着急升级新版。。。

**Comment by gzzyyt** [comment]
我个人比较喜欢追求最新版，而且主要是翻译的问题，我想着升级新版后有可能天气翻译就正常了，就升级试试，我现在已经退回旧版了，等您这边修复了我就再升级，

**Comment by gzzyyt** [comment]
上次升级2023.5.4以后，灯和开关的实体翻译就变成中文了， 但是天气还没有翻译过来，有可能2023.6.0就修复了，您也可以升级后然后修复以后试试

**Comment by c1pher-cn** [comment]
c

**Comment by c1pher-cn** [comment]
天气的问题 我昨天又试了好久，然后看到官方文档上好像说天气默认带翻译，我建议等等
These weather conditions are included in our translation files and also show the corresponding icon.
This means that the weather platforms don't need to support languages.

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/65ee9a94-8a57-49eb-bd00-e477644aaa3a)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/5f6c4bea-25d3-4c33-ba9f-213675569632)
打开所有.py文件搜索里面的yield from替换成await

将@asyncio.coroutine
def xxx  这种改成 async def xxx

如果@asyncio.coroutine下面的那行已经是async def xxx  那就直接把@asyncio.coroutine删除掉

根据论坛这位大佬的提示，这边改了下，已经正常了，我把改好的文件打包发在您帖子回复里。

**Comment by gzzyyt** [comment]
@c1pher-cn 但是天气状态英文的问题可能官方这个版本还没修复，等等吧。

**Comment by c1pher-cn** [comment]
新版本运行不起来的问题我会弄下，好了第一时间跟你说

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/a91bd9b2-e161-40c6-8b48-6d46bdc0151b)
我改后已经可以运行起来，您到帖子里下载尝试下，没问题了，

**Comment by gzzyyt** [comment]
您homeassistant论坛帖子最下面的回复，您看下

**Comment by airwb** [comment]
天气崩了，期待修复

**Comment by c1pher-cn** [comment]
已修复，请各位更新 每个目录里的.py文件
@gzzyyt @airwb
