### ISSUE TITLE
大佬，能看下这个日志里的错误提示是什么意思吗？

### ISSUE THREAD

**Issue by gzzyyt** [c1pher-cn/heweather#13]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/acb1081a-6b00-4e51-a441-e644d14f57f9)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/e6fb3ca3-ca92-48a4-a57f-dd66661c2467)

**Comment by gzzyyt** [comment]
是字符数超了吗？有解决办法吗？

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/7eb830c9-a021-4fe0-8d96-720d5b647af4)
{"code":"200","updateTime":"2023-06-15T09:28+08:00","fxLink":"https://www.qweather.com/severe-weather/zhaoyuan-101120506.html","warning":[{"id":"10112050620230615062600469183110","sender":"山东省气象台","pubTime":"2023-06-15T06:26+08:00","title":"山东省气象台继续发布高温橙色预警","startTime":"2023-06-15T06:26+08:00","endTime":"2023-06-16T06:27+08:00","status":"update","level":"橙色","severity":"Severe","severityColor":"Orange","type":"1009","typeName":"高温","urgency":"","certainty":"","text":"山东省气象台于6月15日06时继续发布高温橙色预警：受大陆暖高压脊影响，15—17日我省将出现高温天气。其中，15—16日，内陆和北部沿海地区38℃左右，局部可达40℃，南部沿海地区23～27℃；17日，鲁西北和鲁中地区36～39℃，南部沿海地区23～27℃，其他地区32～35℃。","related":"10112050620230614161600772913906"},{"id":"10112050620230614160000815320172","sender":"招远市气象台","pubTime":"2023-06-14T16:00+08:00","title":"招远市气象台发布高温黄色预警[Ⅲ/较重]","startTime":"2023-06-14T16:00+08:00","endTime":"2023-06-17T16:02+08:00","status":"active","level":"黄色","severity":"Moderate","severityColor":"Yellow","type":"1009","typeName":"高温","urgency":"","certainty":"","text":"招远市气象台2023年06月14日16时00分发布高温黄色预警信号：受大陆暖高压脊影响，预计15～17日，我市全部镇街将出现高温天气，最高气温可达35℃以上，局部地区超过37℃。请注意防范高温天气对户外作业、城市生活等带来的不利影响。","related":""}],"refer":{"sources":["12379"],"license":["CC BY-SA 4.0"]}}

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/bef04fe6-e23a-47a1-a4e8-a5b728e3f853)
如果是state的字数不允许超过255，那有没有办法把自然灾害预警像彩云天气一样，写到属性里

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/b1b0f585-7421-4e1a-ad5e-721f320eaf83)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/96df6e20-3457-4bcb-951b-f94c83db48c3)
经测试，一条的情况下加上标题也有可能超255字符，何况我这边今天看到的是两条信息，加起来有500多个字符了，肯定超了，我找了个一条的地区，然后加上标题也是超过255字符了，我这边在代码里把标题去掉了，可以正常显示
![image](https://github.com/c1pher-cn/heweather/assets/25847375/0bf49b40-878c-450d-b50c-5a3017b87db6)

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/f0be1586-68d0-40f4-81f2-de2a3597fc4f)
临时解决方案，不让他合并显示了，把标题去掉，添加了listall和listtitle两个列表，for循环时循环添加，然后取第一条（即最新发布的一条），还是希望大佬有时间的话尝试看能不能写到属性里，state里的最大长度确实是255，我这边删掉标题才勉强不超过255
![image](https://github.com/c1pher-cn/heweather/assets/25847375/9dbc8df7-88a0-4301-a25b-b7aad7546e7c)
![image](https://github.com/c1pher-cn/heweather/assets/25847375/014f92a9-175d-4bbf-8d25-5d7530a63e67)
加上标题的话280多个字符了，

**Comment by c1pher-cn** [comment]
嗯 是字数超了，我也遇到过

gzzyyt ***@***.***> 于2023年6月15日周四 11:49写道：

**Comment by c1pher-cn** [comment]
你可以提个合并，我合到主干

Liu MingYu ***@***.***> 于2023年6月15日周四 15:13写道：

**Comment by gzzyyt** [comment]
关键是我这个也不是解决办法，如果字符数超过255的话 还是会报错的，所以没必要上传吧，只是临时解决一下我的问题，如果哪天气象台发布的通知超过255字符了，不还是白搭。 所以我想您能否有时间看能不能写到属性里，然后每一条自然灾害预警都可以显示。我这样只能显示一条，治标不治本啊，临时解决一下！

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/4bd64ea3-dd8b-4747-8dab-a290f8cecffb)
大佬，我不会发合并，我看着属性里的unit_of_measurement没用，我就给写到unit_of_measurement里了，这个应该是计量单位，没什么用，具体的我发到您帖子最下方回复里了，如果您看有什么问题， 就再给优化下，然后可以发布个新版！

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/f226cfeb-85a8-49e4-8625-f87b531641e9)
写到属性里以后没有字符限制了，可以多条信息都合并展示出来

**Comment by c1pher-cn** [comment]
好的，感谢，我周末弄弄

**Comment by gzzyyt** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/25847375/5975ddf6-6fae-4f34-b1b1-1f1f3a26c48e)
天气翻译问题，升级到2023.6.2以后，就可以正常显示中文了

**Comment by c1pher-cn** [comment]
heweather/sensor.py
灾害预警长度问题已经修复，加了一个states属性，有灾害sensor状态会变成on，然后再去读states即可
![image](https://github.com/c1pher-cn/heweather/assets/13911935/8b72ebf6-66b2-4b74-9925-5069573862bb)
