### ISSUE TITLE
大佬请问这个错误怎么解决？custom_components.heweather_forecast.weather::LocalWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

### ISSUE THREAD

**Issue by qy19920913** [c1pher-cn/heweather#14]
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:278
Integration: 天气 ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 10:53:10 (1 occurrences)
Last logged: 10:53:10

custom_components.heweather_forecast.weather::LocalWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration

这个是要更新什么吗？

**Comment by c1pher-cn** [comment]
不影响插件工作，可以先忽略，这个报错我暂时也不知道需要改哪里

qy19920913 ***@***.***> 于2023年7月10日周一 11:00写道：

**Comment by c1pher-cn** [comment]
先关掉，不影响使用暂时不动
