### ISSUE TITLE
大佬,有考虑集成到HACS吗,否则很多人使用起来成本较大

### ISSUE THREAD

**Issue by DUWENINK** [c1pher-cn/heweather#15]
特别是更新,每次都需要重新配置,如果集成到HACS将会有更多人进行下载安装

**Comment by c1pher-cn** [comment]
考虑了 只是没时间弄

**Comment by VergilGao** [comment]
> 考虑了 只是没时间弄

我参考了几个其他hacs的库，还没发现一个集成提供多个传感器需要怎么写，如果有类似的资料，我上班摸鱼的时候就可以尝试帮忙重构一下代码了。

**Comment by VergilGao** [comment]
目前一个比较尴尬的问题：
![image](https://github.com/c1pher-cn/heweather/assets/8655163/4d6cc06a-84c4-4e6d-b388-acdbca096a88)
这里左上角的icon无法反映出当前的天气状态

**Comment by c1pher-cn** [comment]
更新并不需要重新配置啊……

在 2023年7月18日星期二，Reynaldo Baltz ***@***.***> 写道：

**Comment by DUWENINK** [comment]
> 

只是目前没有配置变更,一个东西,证明存在很容易,证明不存在很难

**Comment by DUWENINK** [comment]
> 目前一个比较尴尬的问题： ![image](https://user-images.githubusercontent.com/8655163/259938484-4d6cc06a-84c4-4e6d-b388-acdbca096a88.png) 这里左上角的icon无法反映出当前的天气状态 左边是ha默认的天气集成，右边是我写的自定义集成

已经Star 关注中

**Comment by c1pher-cn** [comment]
![Uploading image.png…]()
我这里正常呢 8.0版本

**Comment by c1pher-cn** [comment]
9.0版本  出现的错误提示fix

**Comment by c1pher-cn** [comment]
同步一下，预计下月底能发到hacs上，目前已经在审核中了
