### ISSUE TITLE
what can i do ?

### ISSUE THREAD

**Issue by xiaonaiquan** [c1pher-cn/heweather#18]
The heweather_forecast custom integration is using deprecated weather forecast
此项在版本 2024.3.0 中无法工作。请在升级之前解决。
The custom integration heweather_forecast implements the forecast property or sets self._attr_forecast in a subclass of WeatherEntity.

Please create a bug report at https://github.com/c1pher-cn/heweather/issues.

Once an updated version of heweather_forecast is available, install it and restart Home Assistant to fix this issue.

**Comment by shangjiazi** [comment]
heweather_forecast::LocalWeather implements the `forecast` property or sets `self._attr_forecast` in a subclass of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please create a bug report at https://github.com/c1pher-cn/heweather/issues

**Comment by c1pher-cn** [comment]
插件内容已经更新，请更新一下插件的相关文件，升级到最新配置即可

**Comment by xiaonaiquan** [comment]
> 插件内容已经更新，请更新一下插件的相关文件，升级到最新配置即可

OK。谢谢
