### ISSUE TITLE
有api马上要取消了

### ISSUE THREAD

**Issue by VergilGao** [c1pher-cn/heweather#2]
custom_components.heweather_forecast.weather::LocalWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

**Comment by c1pher-cn** [comment]
谢谢反馈，我了解一下，是新升级之后提示的么？你ha啥版本的，我的好像没提示

**Comment by VergilGao** [comment]
2022.10.3
因为是docker安装的，提示是在docker logs 里看到的

**Comment by c1pher-cn** [comment]
等他不支持了我再更新下吧。。。我完全没看出来他要停用哪些东西，后面出新的了照着错误改容易点 哈哈哈

**Comment by tata9898** [comment]
加 1 
custom_components.heweather_forecast.weather::LocalWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

**Comment by c1pher-cn** [comment]
我已经升级到2023.1了 还能正常用

**Comment by c1pher-cn** [comment]
研究了一下，计划这次把插件上到hacs里，跟这个问题一起解决

tata9898 ***@***.***> 于2023年1月16日周一 18:23写道：

**Comment by c1pher-cn** [comment]
麻烦二位更新weather文件验证下 @VergilGao @tata9898
