### ISSUE TITLE
LENGTH_KILOMETERS was used from heweather, this is a deprecated constant which will be removed in HA Core 2025.1. 

### ISSUE THREAD

**Issue by devang2** [c1pher-cn/heweather#24]
日志记录器: homeassistant.const
来源: helpers/deprecation.py:197
首次出现: 12:37:47 (16 次总计出现)
上次记录: 12:37:49

LENGTH_KILOMETERS was used from heweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please report it to the author of the 'heweather' custom integration
PRESSURE_HPA was used from heweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please report it to the author of the 'heweather' custom integration
SPEED_KILOMETERS_PER_HOUR was used from heweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please report it to the author of the 'heweather' custom integration
PRECIPITATION_MILLIMETERS_PER_HOUR was used from heweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolumetricFlux.MILLIMETERS_PER_HOUR instead, please report it to the author of the 'heweather' custom integration
TEMP_CELSIUS was used from heweather, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'heweather' custom integration

**Comment by c1pher-cn** [comment]
收到

**Comment by crhan** [comment]
目前仍然出现这个报错~

**Comment by c1pher-cn** [comment]
你们ha是啥版本的？ 我这没出现这个错误呀

**Comment by crhan** [comment]
最新的稳定版 2024.10.4

**Comment by c1pher-cn** [comment]
v1.0.3版本已修正，hacs里升级试一下
