### ISSUE TITLE
配置

### ISSUE THREAD

**Issue by richard-x** [c1pher-cn/heweather#4]
大佬 ，。我在Git上下载了文件放入custom_components目录后除了写配置文件之外我还需要做什么吗？，请问 配置文件写在哪里呢？是在HA里写？还是在目录里面新建yaml文件来做配置呢？如果新建的各个配置是在一个文件里面还是在其对应的文件夹里面呢？谢谢

**Comment by c1pher-cn** [comment]
b站交流

**Comment by AbianTang** [comment]
同问
