### ISSUE TITLE
Home Assistant 2023.6.0插件报错

### ISSUE THREAD

**Issue by miaoyanginfo** [c1pher-cn/heweather#6]
![image](https://user-images.githubusercontent.com/20718488/236718267-0d595cd9-d319-4744-b338-2425bce7d6a2.png)
![image](https://user-images.githubusercontent.com/20718488/236718289-55bf4c20-9833-4708-8fb4-ce35ffcc8949.png)

Platform error sensor.heweather_hourlyforecast - Exception importing custom_components.heweather_hourlyforecast.sensor
Platform error weather.heweather_forecast - Exception importing custom_components.heweather_forecast.weather

**Comment by c1pher-cn** [comment]
收到，最近比较忙，下周我升级看一下

miaoyang ***@***.***> 于2023年5月8日周一 10:09写道：

**Comment by c1pher-cn** [comment]
![image](https://github.com/c1pher-cn/heweather/assets/13911935/9a76caca-6587-441b-b713-fdc8ffbb5a0f)
昨天升级到了最新版本，没有你提到的问题，另外你升的是dev开发版，我不会保证开发版的情况。
目前插件已知问题是天气（weather）实体的英文问题，
![image](https://github.com/c1pher-cn/heweather/assets/13911935/97b107ce-5aaa-4961-ba6c-97fc39c3cde3)
