### ISSUE TITLE
大佬，升级2023.5.2以后，发现heweather 这个插件无法使用，日志里报错

### ISSUE THREAD

**Issue by gzzyyt** [c1pher-cn/heweather#7]
就是这个第三个这个插件无法使用，望修复！
![image](https://user-images.githubusercontent.com/25847375/236748204-61fa85bc-f43a-4fa2-b9cf-d54ba7dd6901.png)
![image](https://user-images.githubusercontent.com/25847375/236748236-b22ae00b-f6e0-446b-9108-469c8820f378.png)

**Comment by c1pher-cn** [comment]
收到，最近比较忙，下周我升级看一下

gzzyyt ***@***.***> 于2023年5月8日周一 14:16写道：

**Comment by c1pher-cn** [comment]
https://devapi.qweather.com/v7/air/now?location=&key=
用你的key和location请求下这个接口看下返回数据，有没有level
这个报错应该跟ha版本没关系，看起来是和风没返回level的数据

**Comment by gzzyyt** [comment]
![image](https://user-images.githubusercontent.com/25847375/236784877-ccd78473-db1c-42a6-aeeb-48f5833f5f70.png)
您看下，是有level的

**Comment by gzzyyt** [comment]
heweather_forecast
heweather_hourlyforecast
lifesuggestion
这三个插件都正常，只有heweather不能用

**Comment by gzzyyt** [comment]
@c1pher-cn ha目前版本如下图
![image](https://user-images.githubusercontent.com/25847375/236785458-35dabc55-9435-4821-94e8-c4513976a572.png)

**Comment by gzzyyt** [comment]
还有一个问题，就是ha升级2023.4.x以后好像所有的实体属性都变成英文了，比如开关的属性默认是开和关，升级后都变成On和off了，天气也一样，如下图， 以前Cloudy显示的是多云，而升级新版后变成Cloudy了  ， 好像只有晴天会显示中文，其他都是英文的，好像要添加一个翻译文件才行，  
![image](https://user-images.githubusercontent.com/25847375/236785997-81001258-a5b5-41e0-86c6-b77f54710866.png)

**Comment by gzzyyt** [comment]
https://bbs.hassbian.com/thread-20364-1-1.html
具体情况这个帖子有发，应该是要手动添加一个翻译文件，翻译过后才能显示中文

**Comment by c1pher-cn** [comment]
1. level这个我建议你重试看看，按这个错误理解就是返回的数据里没有level，我代码里没做校验。
2. 翻译这个我下礼拜研究下，可能就是官方要求的翻译配置有变化，原来都是代码里都是有翻译的，我看看新文档对照着改一下应该就可以了

**Comment by gzzyyt** [comment]
@c1pher-cn 大佬您看我按您的那个要求测试过了，确实也返回level，您看能否您把ha版本升级到2023.5.2最新版然后在测试看下

**Comment by c1pher-cn** [comment]
收到，昨天升级到最新版了，只有这个英文的问题。我研究一下

**Comment by lvyjay** [comment]
> 收到，昨天升级到最新版了，只有这个英文的问题。我研究一下


customize.yaml里设置下翻译


    sensor.heweather_disaster_warn:
       friendly_name: 灾害预警信息
    sensor.heweather_temperature:
       friendly_name: 温度
    sensor.heweather_humidity:
       friendly_name: 湿度
    sensor.heweather_category:
       friendly_name: 空气质量
    sensor.heweather_feelsLike:
       friendly_name: 体感温度
    sensor.heweather_text:
       friendly_name: 天气情况
    sensor.heweather_windDir:
       friendly_name: 风向
    sensor.heweather_windScale:
       friendly_name: 风力
    sensor.heweather_windSpeed:
       friendly_name: 风速度
    sensor.heweather_pressure:
       friendly_name: 大气压强
    sensor.heweather_vis:
       friendly_name: 能见度
    sensor.heweather_cloud:
       friendly_name: 云量
    sensor.heweather_dew:
       friendly_name: 露点温度
    sensor.heweather_precip:
       friendly_name: 当前小时累计降水量
    sensor.heweather_qlty:
       friendly_name: AQI空气质量
    sensor.heweather_level:
       friendly_name: 空气质量级别
    sensor.heweather_primary:
       friendly_name: 主要污染物
    sensor.heweather_pm25:
       friendly_name: PM2.5
    sensor.heweather_pm10:
       friendly_name: PM10
    sensor.heweather_co:
       friendly_name: 一氧化氮
    sensor.heweather_so2:
       friendly_name: 二氧化硫
    sensor.heweather_no2:
       friendly_name: 二氧化氮
    sensor.heweather_o3:
       friendly_name: 臭氧


    sensor.suggestion_air:
       friendly_name: 空气质量
    sensor.suggestion_comf:
       friendly_name: 舒适指数
    sensor.suggestion_cw:
       friendly_name: 洗车指数
    sensor.suggestion_drsg:
       friendly_name: 穿衣指数
    sensor.suggestion_flu:
       friendly_name: 感冒指数    
    sensor.suggestion_sport:
       friendly_name: 运动指数
    sensor.suggestion_trav:
       friendly_name: 旅行指数
    sensor.suggestion_uv:
       friendly_name: 紫外线指数
    sensor.suggestion_sunglass:
       friendly_name: 太阳镜指数
    sensor.suggestion_guomin:
       friendly_name: 过敏指数
    sensor.suggestion_liangshai:
       friendly_name: 晾晒指数
    sensor.suggestion_fangshai:
       friendly_name: 防晒指数
    sensor.suggestion_kongtiao:
       friendly_name: 空调指数


    sensor.remind:
       friendly_name: 小时天气预警
    sensor.hourly_forcast_1:
       friendly_name: 1小时天气预报
    sensor.hourly_forcast_3:
       friendly_name: 3小时天气预报
    sensor.hourly_forcast_6:
       friendly_name: 6小时天气预报
    sensor.hourly_forcast_9:
       friendly_name: 9小时天气预报

**Comment by gzzyyt** [comment]
@lvyjay 是天气英文，晴，阴，雨天，雪天，大雾这些，你发的这个翻译没用吧

**Comment by gzzyyt** [comment]
@lvyjay 比如多云他正常应该显示多云，而他显示Cloudy

**Comment by lvyjay** [comment]
![20230522114110](https://github.com/c1pher-cn/heweather/assets/95771127/dd98be59-8fdd-4e6a-8780-bfd915c16a7f)

不清楚 ，我这些是对的 没有单独的用UI卡片

**Comment by c1pher-cn** [comment]
> > 收到，昨天升级到最新版了，只有这个英文的问题。我研究一下
> 
> customize.yaml里设置下翻译
> 
> ```
> sensor.heweather_disaster_warn:
>    friendly_name: 灾害预警信息
> sensor.heweather_temperature:
>    friendly_name: 温度
> sensor.heweather_humidity:
>    friendly_name: 湿度
> sensor.heweather_category:
>    friendly_name: 空气质量
> sensor.heweather_feelsLike:
>    friendly_name: 体感温度
> sensor.heweather_text:
>    friendly_name: 天气情况
> sensor.heweather_windDir:
>    friendly_name: 风向
> sensor.heweather_windScale:
>    friendly_name: 风力
> sensor.heweather_windSpeed:
>    friendly_name: 风速度
> sensor.heweather_pressure:
>    friendly_name: 大气压强
> sensor.heweather_vis:
>    friendly_name: 能见度
> sensor.heweather_cloud:
>    friendly_name: 云量
> sensor.heweather_dew:
>    friendly_name: 露点温度
> sensor.heweather_precip:
>    friendly_name: 当前小时累计降水量
> sensor.heweather_qlty:
>    friendly_name: AQI空气质量
> sensor.heweather_level:
>    friendly_name: 空气质量级别
> sensor.heweather_primary:
>    friendly_name: 主要污染物
> sensor.heweather_pm25:
>    friendly_name: PM2.5
> sensor.heweather_pm10:
>    friendly_name: PM10
> sensor.heweather_co:
>    friendly_name: 一氧化氮
> sensor.heweather_so2:
>    friendly_name: 二氧化硫
> sensor.heweather_no2:
>    friendly_name: 二氧化氮
> sensor.heweather_o3:
>    friendly_name: 臭氧
> 
> 
> sensor.suggestion_air:
>    friendly_name: 空气质量
> sensor.suggestion_comf:
>    friendly_name: 舒适指数
> sensor.suggestion_cw:
>    friendly_name: 洗车指数
> sensor.suggestion_drsg:
>    friendly_name: 穿衣指数
> sensor.suggestion_flu:
>    friendly_name: 感冒指数    
> sensor.suggestion_sport:
>    friendly_name: 运动指数
> sensor.suggestion_trav:
>    friendly_name: 旅行指数
> sensor.suggestion_uv:
>    friendly_name: 紫外线指数
> sensor.suggestion_sunglass:
>    friendly_name: 太阳镜指数
> sensor.suggestion_guomin:
>    friendly_name: 过敏指数
> sensor.suggestion_liangshai:
>    friendly_name: 晾晒指数
> sensor.suggestion_fangshai:
>    friendly_name: 防晒指数
> sensor.suggestion_kongtiao:
>    friendly_name: 空调指数
> 
> 
> sensor.remind:
>    friendly_name: 小时天气预警
> sensor.hourly_forcast_1:
>    friendly_name: 1小时天气预报
> sensor.hourly_forcast_3:
>    friendly_name: 3小时天气预报
> sensor.hourly_forcast_6:
>    friendly_name: 6小时天气预报
> sensor.hourly_forcast_9:
>    friendly_name: 9小时天气预报
> ```

他说的是天气状态的英文翻译问题，不是这个，这些在ha网页里就直接可以改

**Comment by c1pher-cn** [comment]
> ，

翻了两天文档和官方的论坛，好像是要在目录里加一个translate.json的配置文件，我自己没测通，暂时没搞定 - - |||

**Comment by gzzyyt** [comment]
@c1pher-cn 您有看这个帖子吗https://bbs.hassbian.com/thread-20364-1-1.html，这个帖子里下面回复附件里有个例子，您可以下载看下他是怎么翻译的

**Comment by c1pher-cn** [comment]
好的，翻译的问题我会继续看一下

**Comment by c1pher-cn** [comment]
暂时fix了翻译的问题我再关注
