### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by techzhou** [c1pher-cn/heweather#9]
通过HACS添加本仓库为自定义存储库 再安装
安装后目录结构为

> [core-ssh ~]$ ls config/custom_components/
hacs                heweather           pyscript            xiaomi_gateway3     xiaomi_miio_cooker  xiaomi_miot
[core-ssh ~]$ ls config/custom_components/heweather/
`__pycache__`      _forecast        _hourlyforecast  manifest.json    sensor.py

配置文件无法正常加载 

是不是安装方式不对

**Comment by c1pher-cn** [comment]
‘HACS添加本仓库为自定义存储库 再安装’
我文档里没有一句话提到过hacs，所以你咋操作的？

**Comment by techzhou** [comment]
问题是文档也没提怎么装啊

**Comment by c1pher-cn** [comment]
1.把custom_components目录里的文件完整的下载到 homeassistant主目录的custom_components里
2.配置yaml
